name: Deploy Riego Inteligente

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Simular despliegue
        run: echo "Desplegando sistema de riego inteligente a GCP..."
